version: '3.8'

services:

  socks5server:
    # container_name: SOCKS_1
    image: ${DOCKER_REGISTRY-}socks5server
    mac_address: 00:15:5D:3D:30:09
    networks:
      tlan:
        # ipv4_address: 10.0.0.151
    build:
      context: .
      dockerfile: SOCKS5Server\Dockerfile
    # ports:
    #   - "1080:1080"

# networks: 
#   tlan:
#     driver: transparent
#     driver_opts: 
#       com.docker.network.windowsshim.interface: External
  
# networks:
#   default:
#     external:
#         name: "tlan"

networks:
  tlan:
    external:
      name: tlan