services:
  proxy1:
    build:
      context: ${GIT_REPO}  # смотри файл .env
      dockerfile: SOCKS5Server/Dockerfile
    image: socks5
    container_name: socks5proxy1
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 10.0.0.151  # через DHCP, простым способом получить нельзя
        mac_address: 02:42:0a:00:00:01
    
  proxy2:
    build:
      context: ${GIT_REPO}
      dockerfile: SOCKS5Server/Dockerfile
    image: socks5
    container_name: socks5proxy2
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 10.0.0.152
        mac_address: 02:42:0a:00:00:02
    
networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0  # замените на ваш интерфейс, например enp3s0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1